# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: Research
    url: /research/
    weight: 2
  - name: Teaching
    url: /teaching/
    weight: 3
  - name: CV
    url: https://usf.box.com/s/k9g864k4o6t23z1psg74t8qr8a5zez93
    weight: 4
